### ISSUE TITLE
Solution Explorer Not Updated when adding/moving files

### ISSUE THREAD

**Issue by fitdev** [fernandoescolar/vscode-solution-explorer#10]
When I add new files, or move existing files, the solution explorer view is not updated (files stay the same way as when they were first loaded).

**Comment by fernandoescolar** [comment]
I am not able to reproduce this bug, would you mind to send me your .sln file and the .xxproj you are using?

**Comment by fitdev** [comment]
So far I have tested it only on *.shproj (Shared Project) files, support for which you just added. Have not checked it on regular csproj files. So the issue might be with just shproj files (though the *.projitems file is updated correctly).

**Comment by fernandoescolar** [comment]
There are some changes between a standard project and a shared project, and in order to make it work in the solution explorer I tested it with a solution created with "Visual Studio for Mac". It is a xamarin project and it works right with the v0.2.11. I guess you have a project or solution with anything different... and I would like to find those differences to make it work right also.

It is not necessary all project, only a .sln and a .shproj file with this bug.
