### ISSUE TITLE
Very slow initial load time

### ISSUE THREAD

**Issue by mikeCGrant** [fernandoescolar/vscode-solution-explorer#220]
Each time I start VSCode, the solution explorer takes a VERY long time to open the solution, seems like it's just scanning for easily 10 minutes. If I try to manually open a .sln file it takes just as long.

Nothing has changed on my machine (win 10) solution explorer has been this slow for me for 2 - 3 weeks now, baffling.

Had other reports of this happening at my place of work. Wondering if anyone else has noticed the issue?

**Comment by fernandoescolar** [comment]
In the latest versions there is a new project loader based on the msbuild specification. This will make it slower than previous versions. But it is more compatible with all project files.

The problem is 10 minutes. On my machine it is a few seconds slower (3/4 sec), never minutes. 

How many projects does your solution have? And what kind of projects are they (dotnet core, .Net Framework, ...)?

**Comment by mikeCGrant** [comment]
Hi Fernando, thanks for the quick reply.

My solution has 18 projects and a mixture of dotnet core and some older framework.

**Comment by fernandoescolar** [comment]
Could you provide me some repo (on github for example) with a solution like yours? A solution that takes a long time to open.

**Comment by mikeCGrant** [comment]
Sorry, I can't it's a business repo unfortunately

**Comment by mikeCGrant** [comment]
Ah, thank you so much Fernando, very speedy changes and help. I appreciate it. I'll let you know how I get on

**Comment by mikeCGrant** [comment]
By the way, my 'in folders and subfolders' setting was already disabled.

**Comment by mikeCGrant** [comment]
Hahaha, well . . . .

Just tested with 0.7.2.
The load time of the solution files has gone from around 10 minutes, to about 2 seconds :) 

Nice work!
