### ISSUE TITLE
NuGet packages manager

### ISSUE THREAD

**Issue by BachiMjavanadze** [fernandoescolar/vscode-solution-explorer#227]
At the moment it's not possible to add a package by clicking on the `Add package` button. Hope it's a upcoming feature.

I suggest show this window when clicking on the `Add package` button:

![image](https://user-images.githubusercontent.com/38082501/195674272-5e55eea8-c35b-42ef-9208-d641460df9f0.png)

If it's not impossible then please add settings that gives ability to call any other extension when you click on the `Add package` button:

`"vssolution.NugetackageExternalExtention": "nugetpackagemanagergui"`

I would take this [extension](https://marketplace.visualstudio.com/items?itemName=aliasadidev.nugetpackagemanagergui).

**Comment by fernandoescolar** [comment]
You can already search and add nuget packages in other faster way:
![vscode-solution-explorer-nuget](https://user-images.githubusercontent.com/3491424/195794437-82d019a0-0122-4b23-bdde-a5991b321d4c.gif)

**Comment by BachiMjavanadze** [comment]
@fernandoescolar
In my case when I click on `Add package` button nothing happens, I can't see this pop-up window

**Comment by fernandoescolar** [comment]
Could you check if you have any nuget.config file in the root folder of the project or in its parent folders?

**Comment by BachiMjavanadze** [comment]
No, I do not have any nuget.config file

**Comment by BachiMjavanadze** [comment]
by the way, package remove button works correctly

**Comment by fernandoescolar** [comment]
And Can you see any error in the developer tools console after clicking in the add package button?

**Comment by BachiMjavanadze** [comment]
No Output, no terminal messages are shown

**Comment by nev-21** [comment]
same problem here, popup doesn't appear after click on + button

**Comment by fernandoescolar** [comment]
> same, not sure what a CPS (dotnet core) project type is as it neither works with ASP.NET CORE empty nor console app
> 
> ![image](https://user-images.githubusercontent.com/8661949/197161611-1a5c9b11-3443-4a83-8616-d13dd534fd6d.png)

Any project you can create with this tool is a CPS project. If your project it is not CPS, you should not see the "+" button or the "add package" menu option.

**Comment by fernandoescolar** [comment]
About the issue, I can't reproduce it so I can't help, could you please provide some log error in the Dev Tools or output panel related to it?

**Comment by nev-21** [comment]
### Debug
Hi @fernandoescolar, I just download v0.7.3 and debugged it. 

- I make a sibling folder with a sln that contains a simple console csproj
- I add to launch.json this: "cwd": "${workspaceFolder}/../../../test/"
- F5
- Press +, nothing happens (popup don't appear)
- Press "Add package" nothing happens

### Then I tried with a breakpoint:

- Put a breakpoint at this line:
https://github.com/fernandoescolar/vscode-solution-explorer/blob/48d4f1ff9f66b36d11b7a37435679d2445ed3d13/src/commands/AddPackageCommand.ts#L16
- It stop at that point when click on "+".
- the project types is "cps" so, it return true
- Then it execute the getActions method of the command:
https://github.com/fernandoescolar/vscode-solution-explorer/blob/ece6ac31a9afd3767358e687f825ada4d3fcea1b/src/SolutionExplorerCommands.ts#L70

### getActions() method when click on "+" or "Add package":

- breakpoint on ```projectFullPath``` returns the correct path (**line 22**).
- breakpoint on ```this.wizard``` return a value (**line 23**)
- breakpoint on ```if (!parameters)```  **is never reached** (**line 29**)  
- so the problem is on line 28:
https://github.com/fernandoescolar/vscode-solution-explorer/blob/48d4f1ff9f66b36d11b7a37435679d2445ed3d13/src/commands/AddPackageCommand.ts#L28


### wizard.run():

- following the stack I arrived this method: ```getNugetFeeds(projectPath: string)```
https://github.com/fernandoescolar/vscode-solution-explorer/blob/48d4f1ff9f66b36d11b7a37435679d2445ed3d13/src/extensions/nuget.ts#L24

- breakpoint on line 25 is reached (the press F5)
- breakpoint on line 72 never reached
- so the problem is inside that do-while:


## THE REAL PROBLEM: do-while

- The projectPath is computed correctly
- The nugetConfigPath in the first loop is wrong:
   ```"c:\\Users\\...\\Downloads\\vscode-solution-explorer-0.7.3\\test\\cli/nuget.config"```
   **NOTICE THE SLASH /**
- exists is false, I don't nuget.config file, but even if I have it, the slash / obviously cause "exists" become false.
- in the second loop, the path is:
   ```"c:\\Users\\...\\Downloads\\vscode-solution-explorer-0.7.3\\test/nuget.config"```
- in the third loop:
   ```"c:\\Users\\...\\Downloads\\vscode-solution-explorer-0.7.3/nuget.config"```
- and so on, until the while was stuck on: 
   ```c:\\/nuget.config```
- I put a console log and each time I press "+" an infinite while loop starts.


## CONCLUSION:
the while is infinite, and the / cause problems.

**Comment by fernandoescolar** [comment]
This is very useful. It seems I didn’t think in windows filesystem when I’m looking for a the nuget.config files. 

Thank you very much!

**Comment by BachiMjavanadze** [comment]
On Windows 10 I still can't add new package, can't see this pop-up window

**Comment by nev-21** [comment]
I tested the new release (v0.7.4) in windows 11 it works perfectly.

**Comment by BachiMjavanadze** [comment]
Ok, I think reason was VSCode portable mode, on regular VSCode everything works... but even on portable version everything works except installing packages

**Comment by BachiMjavanadze** [comment]
After reinstalling `VSCode portable mode` everything works fine. Thanks!
