### ISSUE TITLE
.NET core is incorrectly assumed when building a solution targeting .NET framework.

### ISSUE THREAD

**Issue by CatGirlsAreLife** [fernandoescolar/vscode-solution-explorer#24]
As much as I like something like this it expects a project.json file when it should really check if any projects in the solution targets .NET core to begin with. If none are found then it should assume .NET framework and not require that file to exist just to build. I hate having to start up VS2017 which is a memory hog just to build my stuff.

**Comment by fernandoescolar** [comment]
This extension doesn't support .Net Framework builds. The "build" command should appears only when you are working with dotnet core projects. It also doesn't load "project.json" projects. So, if you can see the build option, and when you click it ask for the project.json file, it seems a problem with the dotnet core SDK you have installed in your machine.

In order to be able to analyze if the error is actually in the extension, Would you mind to give me more details about your solution an project file?

**Comment by CatGirlsAreLife** [comment]
Sure, the project files and solution files are here to clone to test: https://github.com/Elskom/Els_kom_new/ at branch add-crc-xml-converter

**Comment by fernandoescolar** [comment]
Solved in next release: Now the solution context menu doesn't show the dotnet core commands if the solution doesn't have any CPS (dotnet core) project.

**Comment by CatGirlsAreLife** [comment]
@fernandoescolar is there a way to extend a vscode extension though to add a .NET framework, and a Mono build option? Although I think it would be nice if all 3 build options was added to this extension and have "Build/Build Solution (.NET Core)", "Build/Build Solution (Mono)", and then "Build/Build Solution (.NET Framework)" then disable the options that do not apply to the solution.
