### ISSUE TITLE
Support codepage 950 console display

### ISSUE THREAD

**Issue by darkmfj** [fernandoescolar/vscode-solution-explorer#36]
Would it be possible to support traditional Chinese console display (codepage 950)?
In win10, the traditional Chinese text appeared to be garbled. Thanks.

![2018-08-31_163352](https://user-images.githubusercontent.com/1712718/44902177-d26f8600-ad3b-11e8-9589-5d6793382a4f.png)

**Comment by fernandoescolar** [comment]
Related #16

**Comment by fernandoescolar** [comment]
I'm using [this](https://github.com/bnoordhuis/node-iconv) library in order to encode properly an output text in console. Could you tell me which one of the following encoding types are the "traditional Chinese":

EUC-CN, HZ, GBK, CP936, GB18030, EUC-TW, BIG5, CP950, BIG5-HKSCS, BIG5-HKSCS:2004, BIG5-HKSCS:2001, BIG5-HKSCS:1999, ISO-2022-CN, ISO-2022-CN-EXT

Thank you in advance,
