### ISSUE TITLE
Feature Request: Track Active Item in Solution Explorer

### ISSUE THREAD

**Issue by ebellumat** [fernandoescolar/vscode-solution-explorer#69]
In traditional Visual Studio, exists one option to track the current opened file on solution explorer. Vs Code have this On by default, but in the solution explorer of this extension, this behaviour dosent exists. If you want, i can implement and create the PR later.

**Comment by fernandoescolar** [comment]
Hi @ebellumat,

Thank you very much for your suggestion. I'm glad to tell you this feature is already implemented and you can activate it using the below vscode user settings parameter:

```
"vssolution.trackActiveItem": true,
```

By default this setting is inactive because it causes behavior problems when you are using this extension in "activity bar" mode. So I also recommend you to change this setting parameter:

```
"vssolution.showMode": "explorer",
```

It will change the place you can find the solution explorer pane. Now it will appear in the first tab ("Explorer").

**Comment by ebellumat** [comment]
Thanks! Works fine now!

**Comment by an-dr-eas-k** [comment]
Hi, somehow this does not work for me. I have the settings as described in the comment above https://github.com/fernandoescolar/vscode-solution-explorer/issues/69#issuecomment-466041977 but the active file is not selected in the editor.

I am on 
Version: 1.40.1 (system setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

cheers

**Comment by nbjgi1** [comment]
Doesn't work for me either, VS Code says those settings aren't known.
